//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class Barco
    {
        public Barco()
        {
            this.Recinto = new HashSet<Recinto>();
            this.Viaje = new HashSet<Viaje>();
        }

        [ScaffoldColumn(false)]
        public int id_barco { get; set; }


        [Required(ErrorMessage = "El nombre del barco es obligatorio")]
        [Display(Name = "Nombre del barco")]
        [StringLength(100, ErrorMessage = "El {0} no debe exceder los 100 caracteres.")]
        public string nombre_barco { get; set; }


        [Display(Name = "Descripción")]
        [StringLength(255, ErrorMessage = "La {0} no debe exceder los 255 caracteres.")]
        public string descripcion { get; set; }

        [Required(ErrorMessage = "Capacidado es obligatoria")]
        [Display(Name = "Capacidad")]
        public int capacidad { get; set; }

        [Required(ErrorMessage = "Seleccione un tipo de barco")]
        [Display(Name = "Tipo de barco")]
        public short id_tipo_barco { get; set; }


        [Required(ErrorMessage = "Seleccione una línea naviera")]
        [Display(Name = "Línea naviera")]
        public int id_linea_naviera { get; set; }


        public virtual LineaNaviera LineaNaviera { get; set; }
        public virtual TipoBarco TipoBarco { get; set; }
        public virtual ICollection<Recinto> Recinto { get; set; }
        public virtual ICollection<Viaje> Viaje { get; set; }
    }

}
