//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Pasajero = new HashSet<Pasajero>();
            this.Puerto = new HashSet<Puerto>();
        }

        [ScaffoldColumn(false)]
        public int id_ciudad { get; set; }

        [Required(ErrorMessage = "El nombre de la ciudad es obligatorio")]
        [Display(Name = "Nombre de la ciudad")]
        [StringLength(100, ErrorMessage = "{0} no debe exceder los 100 caracteres.")]
        [RegularExpression(@"^[a-zA-ZñÑáéíóú]{1}[a-zA-ZñÑáéíóú ]{1,}$", ErrorMessage = "Solo letras.")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Seleccione una división administrativa")]
        [Display(Name = "División administrativa")]
        public int id_division_administrativa { get; set; }

        public virtual DivisionAdministrativa DivisionAdministrativa { get; set; }
        public virtual ICollection<Pasajero> Pasajero { get; set; }
        public virtual ICollection<Puerto> Puerto { get; set; }
    }

}
