//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ImagineProject.Models
{
    public partial class Db_ImagineEntities : DbContext
    {
        public Db_ImagineEntities()
            : base("name=Db_ImagineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Barco> Barcos { get; set; }
        public DbSet<Ciudad> Ciudades { get; set; }
        public DbSet<DivisionAdministrativa> DivisionesAdministrativas { get; set; }
        public DbSet<LineaNaviera> LineasNavieras { get; set; }
        public DbSet<Movimiento> Movimientos { get; set; }
        public DbSet<OrigenDestino> OrigenDestinos { get; set; }
        public DbSet<Pais> Paises { get; set; }
        public DbSet<Pasaje> Pasajes { get; set; }
        public DbSet<Pasajero> Pasajeros { get; set; }
        public DbSet<Portico> Porticos { get; set; }
        public DbSet<Puerto> Puertos { get; set; }
        public DbSet<Recinto> Recintos { get; set; }
        public DbSet<RecintoPortico> RecintoPorticos { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TipoAmbiente> TiposAmbientes { get; set; }
        public DbSet<TipoBarco> TiposBarcos { get; set; }
        public DbSet<TipoDivision> TiposDivisiones { get; set; }
        public DbSet<TipoMovimiento> TiposMovimientos { get; set; }
        public DbSet<TipoPasaje> TiposPasajes { get; set; }
        public DbSet<TipoRecinto> TiposRecintos { get; set; }
        public DbSet<TipoViaje> TiposViajes { get; set; }
        public DbSet<TipoZona> TipoZonas { get; set; }
        public DbSet<Viaje> Viajes { get; set; }
        public DbSet<Zona> Zonas { get; set; }
        public DbSet<ZonaPais> ZonaPaises { get; set; }
    }
}
