//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ImagineProject.Models
{
    public partial class DWH_ImagineEntities : DbContext
    {
        public DWH_ImagineEntities()
            : base("name=DWH_ImagineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dim_barco> dim_barcos { get; set; }
        public DbSet<dim_escala> dim_escalas { get; set; }
        public DbSet<dim_pasaje> dim_pasajes { get; set; }
        public DbSet<dim_pasajero> dim_pasajeros { get; set; }
        public DbSet<dim_recinto> dim_recintos { get; set; }
        public DbSet<dim_tiempo> dim_tiempos { get; set; }
        public DbSet<dim_viaje> dim_viajes { get; set; }
        public DbSet<fact_movimiento> fact_movimientos { get; set; }
    }
}
