//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ImagineProject.Models
{
    public partial class dim_viaje
    {
        public dim_viaje()
        {
            this.dim_escala = new HashSet<dim_escala>();
            this.dim_pasaje = new HashSet<dim_pasaje>();
            this.fact_movimientos = new HashSet<fact_movimiento>();
        }
    
        public long id_viaje { get; set; }
        public string tipo_viaje { get; set; }
        public string descripcion_tipo_viaje { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public System.DateTime fecha_llegada { get; set; }
        public string descripcion_viaje { get; set; }
        public string puerto_origen { get; set; }
        public string puerto_destino { get; set; }
    
        public virtual ICollection<dim_escala> dim_escala { get; set; }
        public virtual ICollection<dim_pasaje> dim_pasaje { get; set; }
        public virtual ICollection<fact_movimiento> fact_movimientos { get; set; }
    }
    
}
