//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ImagineProject.Models
{
    public partial class dim_escala
    {
        public long id_escala { get; set; }
        public string pais { get; set; }
        public string division_administrativa { get; set; }
        public string ciudad { get; set; }
        public string puerto_escala { get; set; }
        public short numero_escala { get; set; }
        public System.DateTime fecha_llegada { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public long id_viaje { get; set; }
    
        public virtual dim_viaje dim_viaje { get; set; }
    }
    
}
