//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ImagineProject.Models
{
    public partial class dim_pasaje
    {
        public long id_pasaje { get; set; }
        public long id_viaje { get; set; }
        public long id_pasajero { get; set; }
        public string tipo_pasaje { get; set; }
        public string descripcion_tipo_pasaje { get; set; }
        public string numero_boleto { get; set; }
    
        public virtual dim_pasajero dim_pasajero { get; set; }
        public virtual dim_viaje dim_viaje { get; set; }
    }
    
}
