//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ImagineProject.Models
{
    public partial class dim_pasajero
    {
        public dim_pasajero()
        {
            this.dim_pasaje = new HashSet<dim_pasaje>();
            this.fact_movimientos = new HashSet<fact_movimiento>();
        }
    
        public long id_pasajero { get; set; }
        public string pasaporte { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string direccion { get; set; }
        public string numero_contacto { get; set; }
        public string e_mail { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
    
        public virtual ICollection<dim_pasaje> dim_pasaje { get; set; }
        public virtual ICollection<fact_movimiento> fact_movimientos { get; set; }
    }
    
}
