//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ImagineProject.Models
{
    public partial class dim_tiempo
    {
        public dim_tiempo()
        {
            this.fact_movimientos = new HashSet<fact_movimiento>();
        }
    
        public long id_tiempo { get; set; }
        public System.DateTime fecha { get; set; }
        public short anio { get; set; }
        public short mes { get; set; }
        public short dia { get; set; }
        public short semana_anio { get; set; }
        public string nombre_mes { get; set; }
        public string dia_semana { get; set; }
    
        public virtual ICollection<fact_movimiento> fact_movimientos { get; set; }
    }
    
}
