//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class DivisionAdministrativa
    {
        public DivisionAdministrativa()
        {
            this.Ciudad = new HashSet<Ciudad>();
        }

        [ScaffoldColumn(false)]
        public int id_division_administrativa { get; set; }

        [Required(ErrorMessage = "El nombre de división es obligatorio")]
        [Display(Name = "Nombre de división")]
        [StringLength(100, ErrorMessage = "El {0} no debe exceder los 100 caracteres.")]
        [RegularExpression(@"^[a-zA-ZñÑáéíóú]{1}[a-zA-ZñÑáéíóú ]{1,}$", ErrorMessage = "Solo letras.")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Seleccione un país")]
        [Display(Name = "País")]
        public int id_pais { get; set; }

        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual Pais Pais { get; set; }
    }

}
