//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ImagineProject.Models
{
    public partial class fact_movimiento
    {
        public long id_fact_movimientos { get; set; }
        public long id_pasajero { get; set; }
        public long id_tiempo { get; set; }
        public long id_barco { get; set; }
        public long id_viaje { get; set; }
        public long id_recinto { get; set; }
        public int cantidad_movimientos { get; set; }
    
        public virtual dim_barco dim_barco { get; set; }
        public virtual dim_pasajero dim_pasajero { get; set; }
        public virtual dim_recinto dim_recinto { get; set; }
        public virtual dim_tiempo dim_tiempo { get; set; }
        public virtual dim_viaje dim_viaje { get; set; }
    }
    
}
