//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class LineaNaviera
    {
        public LineaNaviera()
        {
            this.Barco = new HashSet<Barco>();
        }

        [ScaffoldColumn(false)]
        public int id_linea_naviera { get; set; }

        [Required(ErrorMessage = "Línea naviera es obligatoria")]
        [Display(Name = "Línea naviera")]
        [StringLength(255, ErrorMessage = "{0} no debe exceder los 255 caracteres.")]
        public string linea_naviera { get; set; }

        public virtual ICollection<Barco> Barco { get; set; }
    }

}
