//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ImagineProject.Models
{
    public partial class Movimiento
    {
        public int id_movimiento { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public int id_portico { get; set; }
        public short id_tipo_movimiento { get; set; }
        public int id_tag { get; set; }
    
        public virtual Portico Portico { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
    }
    
}
