//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class OrigenDestino
    {
        [ScaffoldColumn(false)]
        public int id_orgen_detino { get; set; }

        [Required(ErrorMessage = "Seleccione puerto de escala")]
        [Display(Name = "Escalas")]
        public int id_puerto { get; set; }

        [Required(ErrorMessage = "Seleccione viaje")]
        [Display(Name = "Viaje")]
        public int id_viaje { get; set; }

        [Required(ErrorMessage = "Número de escala es obligatorio")]
        [Display(Name = "Número de escala")]
        public int prioridad { get; set; }

        [Required(ErrorMessage = "Fecha de llegada es obligatoria")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        [Display(Name = "Fecha de llegada")]
        public System.DateTime fecha_llegada { get; set; }

        [Required(ErrorMessage = "Fecha de salida es obligatoria")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        [Display(Name = "Fecha de salida")]
        public System.DateTime fecha_salida { get; set; }

        public virtual Puerto Puerto { get; set; }
        public virtual Viaje Viaje { get; set; }
    }

}
