//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class Portico
    {
        public Portico()
        {
            this.Movimiento = new HashSet<Movimiento>();
            this.RecintoPortico = new HashSet<RecintoPortico>();
        }

        [ScaffoldColumn(false)]
        public int id_portico { get; set; }

        [Required(ErrorMessage = "Número de portico es obligatorio")]
        [Display(Name = "Número de portico")]
        public int numero_portico { get; set; }

        [Required(ErrorMessage = "Dirección IP es obligatorio")]
        [Display(Name = "Dirección IP")]
        [StringLength(100, ErrorMessage = "{0} no debe exceder los 100 caracteres.")]
        public string descripcion_portico { get; set; }

        [ScaffoldColumn(false)]
        public bool estado { get; set; }

        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual ICollection<RecintoPortico> RecintoPortico { get; set; }
    }

}
