//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class RecintoPortico
    {

        [Required(ErrorMessage = "Seleccione portico")]
        [Display(Name = "Portico")]
        public int id_portico { get; set; }

        [Required(ErrorMessage = "Seleccione recinto")]
        [Display(Name = "Recinto")]
        public int id_recinto { get; set; }

        [ScaffoldColumn(false)]
        public bool estado { get; set; }

        public virtual Portico Portico { get; set; }
        public virtual Recinto Recinto { get; set; }
    }

}
