//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class Tag
    {
        public Tag()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }

        [ScaffoldColumn(false)]
        public int id_tag { get; set; }

        /*
        [Required(ErrorMessage = "Identificador es obligatorio")]
        [Display(Name = "Identificador")]
        [StringLength(255, ErrorMessage = "El {0} no debe exceder los 255 caracteres.")]
        */
        
        //[ScaffoldColumn(false)]
        [Required(ErrorMessage = "Ingrese el ID de la pulsera")]
        [Display(Name = "Identificador")]
        [StringLength(24, MinimumLength = 24)]//, ErrorMessage = "ijijij")]
        public string identificador { get; set; }

        [ScaffoldColumn(false)]
        public System.DateTime fecha_registro { get; set; }

        [ScaffoldColumn(false)]
        public bool estado { get; set; }

        [Required(ErrorMessage = "Seleccione pasajero")]
        [Display(Name = "Pasajero")]
        public int id_pasajero { get; set; }
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual Pasajero Pasajero { get; set; }
    }

}
