//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class TipoZona
    {
        public TipoZona()
        {
            this.Zona = new HashSet<Zona>();
        }

        [ScaffoldColumn(false)]
        public short id_tipo_zona { get; set; }

        [Required(ErrorMessage = "Tipo de zona es obligatoria")]
        [Display(Name = "Tipo de zona")]
        [StringLength(30, ErrorMessage = "{0} no debe exceder los 30 caracteres.")]
        [RegularExpression(@"^[a-zA-ZÒ—·ÈÌÛ˙]{1}[a-zA-ZÒ—·ÈÌÛ˙ ]{1,}$", ErrorMessage = "Solo letras.")]
        public string tipo_zona { get; set; }

        public virtual ICollection<Zona> Zona { get; set; }
    }

}
