//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class TipoRecinto
    {
        public TipoRecinto()
        {
            this.Recinto = new HashSet<Recinto>();
        }

        [ScaffoldColumn(false)]
        public short id_tipo_recinto { get; set; }

        [Required(ErrorMessage = "Tipo de recinto es obligatorio")]
        [Display(Name = "Tipo de recinto")]
        [StringLength(100, ErrorMessage = "El {0} no debe exceder los 100 caracteres.")]
        public string tipo_recinto { get; set; }

        public virtual ICollection<Recinto> Recinto { get; set; }
    }

}
