//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class TipoMovimiento
    {
        public TipoMovimiento()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }

        [ScaffoldColumn(false)]
        public short id_tipo_movimiento { get; set; }

        [Required(ErrorMessage = "Tipo de movimiento es obligatorio")]
        [Display(Name = "Tipo de movimiento")]
        [StringLength(20, ErrorMessage = "El {0} no debe exceder los 20 caracteres.")]
        public string tipo_movimiento { get; set; }

        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }

}
