//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class TipoViaje
    {
        public TipoViaje()
        {
            this.Viaje = new HashSet<Viaje>();
        }

        [ScaffoldColumn(false)]
        public short id_tipo_viaje { get; set; }

        [Required(ErrorMessage = "Tipo de viaje es obligatorio")]
        [Display(Name = "Tipo de viaje")]
        [StringLength(50, ErrorMessage = "El {0} no debe exceder los 50 caracteres.")]
        public string tipo_viaje { get; set; }

        [Required(ErrorMessage = "Descripción es obligatoria")]
        [Display(Name = "Descripción")]
        [StringLength(255, ErrorMessage = "El {0} no debe exceder los 255 caracteres.")]
        public string descripcion { get; set; }

        public virtual ICollection<Viaje> Viaje { get; set; }
    }

}
