//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class TipoDivision
    {
        public TipoDivision()
        {
            this.Pais = new HashSet<Pais>();
        }

        [ScaffoldColumn(false)]
        public short id_tipo_division { get; set; }

        [Required(ErrorMessage = "Tipo de división administrativa es obligatoria")]
        [Display(Name = "Tipo de división administrativa")]
        [StringLength(30, ErrorMessage = "{0} no debe exceder los 30 caracteres.")]
        public string tipo_division { get; set; }

        public virtual ICollection<Pais> Pais { get; set; }
    }

}
