//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImagineProject.Models
{
    public partial class Zona
    {
        public Zona()
        {
            this.ZonaPais = new HashSet<ZonaPais>();
        }

        [ScaffoldColumn(false)]
        public int id_zona { get; set; }

        [Required(ErrorMessage = "Nombre de zona es obligatorio")]
        [RegularExpression(@"^[a-zA-ZÒ—·ÈÌÛ˙]{1}[a-zA-ZÒ—·ÈÌÛ˙ ]{1,}$", ErrorMessage = "Solo letras.")]
        [Display(Name = "Nombre de zona")]
        public string nombre_zona { get; set; }

        [Required(ErrorMessage = "Seleccione tipo de zona")]
        [Display(Name = "Tipo de zona")]
        public short id_tipo_zona { get; set; }

        public virtual TipoZona TipoZona { get; set; }
        public virtual ICollection<ZonaPais> ZonaPais { get; set; }
    }

}
